person:
  
  #  单引号会将 \n作为字符串输出   双引号会将\n 作为换行输出
  #  双引号不会转义，单引号会转义
  userName: "zhangsan \n nihao"
  boss: true
  birth: 2022/4/22
  age: 18
#  数组写法
#  interests: [篮球 , 足球]
  interests: 
    - 篮球
    - 足球
    - 18
#  list
  animal: [阿毛 , 阿狗]
#  map写法
#  score: 
#    english: 80
#    math: 90
  score: [english: 80 , math: 70]
  salarys: 
    - 999.3
    - 654.8
    - 7657
#    类
  pet:
    name: 阿狗
    weight: 99.88
#    复杂map
  allPets:
    sick: 
      - {name: 阿狗 , weight: 99.99}
      - name: 阿毛
        weight: 88.4
      - name: 啊冲
        weight: 76.3
    heath: 
      - {name: 校花 , weight: 199.22}
      - {name: 小明 , weight: 200.32}