spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    # springboot2.1版本以上内置的mysql版本是8,  2.1版本一下内置的是5
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatisplus?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
mybatis-plus:
  configuration:
    # 配置mybatis的sql语句输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启下划线转驼峰    
    # map-underscore-to-camel-case: true
  # 设置mybatis的全局配置
  global-config:
    db-config:
      # 设置实体类对应表的统一前缀
      table-prefix: t_
      # 设置统一的主键生成策略; auto主键递增，根据最大的进行递增
      id-type: auto   
  # 配置类型别名对应的包
  type-aliases-package: codewater.mybatisplus.pojo
  # 扫描通用枚举的包
  type-enums-package: codewater.mybatisplus.enums